### ISSUE TITLE
Can this script be used in oracle 11g database?

### ISSUE THREAD

**Issue by cityvigil** [carlos-sierra/cscripts#1]
I found that this script does not support 11g, is there an easy modification that can support 11g db  . :)

**Comment by carlos-sierra** [comment]
not sure what script are you referring to. but most of my scripts were developed and tested on 12.1.0.2. then some may not work "as is" on prior releases.

**Comment by cityvigil** [comment]
For example, the script cs_**ash_analytics.sql** is executed on 11.2.0.4
`Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning and Data Mining options

09:20:40 SYS at orcl >@aa.sql

..................

Elapsed: 00:00:00.01
ALTER SESSION SET "_px_cdb_view_enabled" = FALSE

ERROR at line 1:
ORA-02248: invalid option for ALTER SESSION

..................
5. Wait Class (opt):
Enter value for 5:
 FETCH FIRST 30 ROWS ONLY
 *
ERROR at line 58:
ORA-00933: SQL command not properly ended


6. Event (opt):
Enter value for 6:
 FETCH FIRST 30 ROWS ONLY
 *
ERROR at line 46:
ORA-00933: SQL command not properly ended

............
10. Reporting Dimension: [{wait_class}|event|machine|sql_id|plan_hash_value|top_level_sql_id|blocking_session|current_obj#|module|pdb_name]
Enter value for 10:



FUNCTION get_sql_text (p_sql_id IN VARCHAR2)
         *
ERROR at line 2:
ORA-00905: missing keyword

...
scp client1:/tmp/oci_dbperf_Z___ORCL__cs_ash_analytics*.* .
scp client1:/tmp/oci_dbperf_*.* .

Use h.sql or help.sql for "cs" scripts inventory by type, and ls.sql for alphabetical list of "cs" scripts.

SQL> @cs_ash_analytics.sql "2021-04-09T09:20:08" "2021-04-09T09:21:11" "1s" "" "" "" "" "" "" "wait_class"
09:21:41 _user 'at' _connect_identifier >
09:21:43 SYS at orcl >
09:22:00 SYS at orcl >exit

` 
I know it can't run on oracle 11g.
but ...I would like to say that the  **cscripts-master** script you wrote is very great.
