### ISSUE TITLE
coe_xfr_sql_profile_ failed with ORA-06532: Subscript outside of limit ORA-06512: at line 9

### ISSUE THREAD

**Issue by norkou** [carlos-sierra/cscripts#3]
Hello Carlos 
I am facing the issue below 
with coe_xfr_sql_profile_2d4vkxwgg5ntk_1668084397.sql

maybe a known issue ?

6280  force_match => FALSE /* TRUE:FORCE (match even when different literals in SQL). FALSE:EXACT (similar to CURSOR_SHARING) */ );
6281  DBMS_LOB.FREETEMPORARY(sql_txt);
6282  END;
6283  /
DECLARE
*
ERROR at line 1:
ORA-06532: Subscript outside of limit
ORA-06512: at line 9

thanks 
N.

**Comment by carlos-sierra** [comment]
I do not recall seen it.

**Comment by norkou** [comment]
Hi  Carlos
I had to recompile some invalid objects and works fine.

**Comment by norkou** [comment]
invalid objects need to be recompiled
